[package]
name = "no_std_dll"
version = "0.1.0"
authors = ["rkr35"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3", features = [
    "libloaderapi",
    "minwindef",
    "processthreadsapi",
    "synchapi",
    "winnt",
]}